apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: HelloWorld
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
